#!/usr/bin/env sh

# Format staged files with prettier
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(css|html|json|js|php)$')

if [ -n "$STAGED_FILES" ]; then
	echo "Formatting staged files..."
	echo "$STAGED_FILES" | xargs npx prettier --write
	echo "$STAGED_FILES" | xargs git add
fi

exit 0
